### ISSUE TITLE
[Documentation] disableKinds taxonomy

### ISSUE THREAD

**Issue by FelixBenning** [amzrk2/hugo-theme-fuji#49]
```toml
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
```

this does not seem to do anything (I tried commenting it out and the tags still seem to work). What is the purpose of this?
