### ISSUE TITLE
How Can I Remove the Tag Icon if There are No Tags

### ISSUE THREAD

**Issue by amarz45** [amzrk2/hugo-theme-fuji#91]
By default, this theme always shows the tag icon and it shows "No tag" if there aren't any. I want it to show nothing if there are no tags. I removed the "No tag" text by removing these lines from `i18n/en.toml`:

```toml
[postMetaNoTag]
    other = "No tag"
```

But it still shows the tag icon. How can I get rid of it?
